### PR TITLE
Ensure create-image.sh doesn't need to be run as root. Escalate via sudo

### PR DESCRIPTION
**Pull request by ankurkotwal**

### CODE REVIEW

**Comment by ankurkotwal** [comment]
Before you merge this, I need to test it some more but thought I'd get your feedback in the meantime.

**Comment by thefossguy** [comment]
Hi, I'll have to reject this particular PR since we need to handle this sooner in the script. I've already implemented this and you can have a look [here](https://github.com/thefossguy/archlinux-visionfive2/commit/2c978ffc45cf6ee1f688bccb23d59d386d2314ff).

Feel free to comment :)

**Comment by ankurkotwal** [comment]
I understand why you've done it this way and it works well.

One thing to consider is that folks won't necessarily be comfortable running scripts off the internet as root. I proposed the sudo escalation for each command since that would mean that devs could scan through the script to see where the root privileges are required.

Happy to close this PR though.

**Comment by thefossguy** [comment]
> One thing to consider is that folks won't necessarily be comfortable running scripts off the internet as root.

Hey that's me! 😅

The main reason why I included an early exit if root escalation wasn't detected versus using `sudo` where necessary is because the script may halt sometimes when waiting for the user to enter their password for `sudo`. The password prompt may timeout too.

**Pull request closed without merging**
